# Generated by Django 5.2.11 on 2026-02-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_promptlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorychunk',
            name='reflection',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
