# Generated by Django 5.2.11 on 2026-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_memorychunk_reflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorychunk',
            name='consolidated',
            field=models.BooleanField(default=False),
        ),
    ]
