# Generated by Django 5.2.15 on 2026-06-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_memorychunk_consolidated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('personality_update', 'Personality Update'), ('profile_update', 'Profile Update'), ('project_doc_write', 'Project Document Write'), ('file_write', 'File Write')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('summary', models.TextField()),
                ('detail', models.JSONField(default=dict)),
                ('auto_approve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='memorychunk',
            name='chunk_type',
            field=models.CharField(choices=[('raw', 'Raw conversation chunk'), ('doc_pointer', 'Pointer to a durable document')], default='raw', max_length=20),
        ),
        migrations.AddField(
            model_name='memorychunk',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memorychunk',
            name='memory_tier',
            field=models.CharField(choices=[('archival', 'Archival (vector search)'), ('core', 'Core (always in context)')], default='archival', max_length=20),
        ),
        migrations.AddField(
            model_name='memorychunk',
            name='target_file',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='memorychunk',
            name='reflection',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['chunk_type', 'is_active'], name='core_memory_chunk_t_77084a_idx'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['memory_tier'], name='core_memory_memory__e07025_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type'], name='core_auditl_action__e03c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model'], name='core_auditl_target__f712bf_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingchange',
            index=models.Index(fields=['status', 'created_at'], name='core_pendin_status_b5ea2c_idx'),
        ),
    ]
