# Generated by Django 5.2.15 on 2026-06-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog_pendingchange_memorychunk_chunk_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('personality', 'Personality'), ('user_profile', 'User Profile'), ('project_doc', 'Project Document'), ('knowledge_file', 'Knowledge File')], max_length=50)),
                ('content_id', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('preference', 'Preference'), ('goal', 'Goal'), ('expertise', 'Expertise'), ('habit', 'Habit'), ('context', 'Context'), ('relationship', 'Relationship'), ('other', 'Other')], max_length=50)),
                ('fact_key', models.CharField(max_length=200)),
                ('fact_value', models.TextField()),
                ('source', models.CharField(blank=True, default='', max_length=500)),
                ('confidence', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('related', 'Related'), ('depends_on', 'Depends On'), ('implements', 'Implements'), ('contradicts', 'Contradicts'), ('refines', 'Refines'), ('supersedes', 'Supersedes'), ('references', 'References')], default='related', max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='core.memorychunk')),
                ('target_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='core.memorychunk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='memorychunk',
            name='lifecycle_stage',
            field=models.CharField(choices=[('inbox', 'Inbox (recently created)'), ('active', 'Active (regularly referenced)'), ('archived', 'Archived (historical reference)'), ('stale', 'Stale (candidate for cleanup)')], default='inbox', max_length=20),
        ),
        migrations.AddIndex(
            model_name='versionsnapshot',
            index=models.Index(fields=['content_type', 'content_id'], name='core_versio_content_0c742e_idx'),
        ),
        migrations.AddIndex(
            model_name='versionsnapshot',
            index=models.Index(fields=['created_at'], name='core_versio_created_3d2dab_idx'),
        ),
        migrations.AddIndex(
            model_name='userfact',
            index=models.Index(fields=['category', 'is_active'], name='core_userfa_categor_f1e0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='userfact',
            index=models.Index(fields=['fact_key'], name='core_userfa_fact_ke_50a27c_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptlink',
            index=models.Index(fields=['link_type'], name='core_concep_link_ty_177c35_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptlink',
            index=models.Index(fields=['source_chunk', 'link_type'], name='core_concep_source__e26397_idx'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['lifecycle_stage'], name='core_memory_lifecyc_25b53a_idx'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['memory_tier', 'is_active', 'lifecycle_stage'], name='core_memory_memory__d0c973_idx'),
        ),
        migrations.AlterField(
            model_name='pendingchange',
            name='change_type',
            field=models.CharField(choices=[('personality_update', 'Personality Update'), ('profile_update', 'Profile Update'), ('project_doc_write', 'Project Document Write'), ('file_write', 'File Write'), ('fact_update', 'Fact Update'), ('core_memory_promote', 'Core Memory Promotion'), ('memory_lifecycle', 'Memory Lifecycle Change')], max_length=50),
        ),
    ]
