# Generated by Django 5.2.15 on 2026-06-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_versionsnapshot_userfact_conceptlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('implemented', 'Implemented'), ('superseded', 'Superseded'), ('rejected', 'Rejected')], default='accepted', max_length=50)),
                ('rationale', models.TextField(blank=True, default='')),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('context', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.decisionrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='decisionrecord',
            index=models.Index(fields=['project', 'status'], name='core_decisi_project_1230f1_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionrecord',
            index=models.Index(fields=['project', 'created_at'], name='core_decisi_project_5edcaa_idx'),
        ),
    ]
