# Generated by Django 6.0.3 on 2026-06-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_decisionrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conceptlink',
            new_name='core_concep_link_ty_2fc87f_idx',
            old_name='core_concep_link_ty_177c35_idx',
        ),
        migrations.RenameIndex(
            model_name='conceptlink',
            new_name='core_concep_source__1407f7_idx',
            old_name='core_concep_source__e26397_idx',
        ),
        migrations.RenameIndex(
            model_name='decisionrecord',
            new_name='core_decisi_project_48ceff_idx',
            old_name='core_decisi_project_1230f1_idx',
        ),
        migrations.RenameIndex(
            model_name='decisionrecord',
            new_name='core_decisi_project_e0f503_idx',
            old_name='core_decisi_project_5edcaa_idx',
        ),
        migrations.RenameIndex(
            model_name='memorychunk',
            new_name='core_memory_lifecyc_c1effd_idx',
            old_name='core_memory_lifecyc_25b53a_idx',
        ),
        migrations.RenameIndex(
            model_name='memorychunk',
            new_name='core_memory_memory__ba8d62_idx',
            old_name='core_memory_memory__d0c973_idx',
        ),
        migrations.RenameIndex(
            model_name='userfact',
            new_name='core_userfa_categor_988140_idx',
            old_name='core_userfa_categor_f1e0e2_idx',
        ),
        migrations.RenameIndex(
            model_name='userfact',
            new_name='core_userfa_fact_ke_8b4110_idx',
            old_name='core_userfa_fact_ke_50a27c_idx',
        ),
        migrations.RenameIndex(
            model_name='versionsnapshot',
            new_name='core_versio_content_9fcdb6_idx',
            old_name='core_versio_content_0c742e_idx',
        ),
        migrations.RenameIndex(
            model_name='versionsnapshot',
            new_name='core_versio_created_5ceffb_idx',
            old_name='core_versio_created_3d2dab_idx',
        ),
    ]
