# Generated by Django 6.0.3 on 2026-06-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_concep_link_ty_177c35_idx_core_concep_link_ty_2fc87f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorychunk',
            name='importance',
            field=models.FloatField(default=0.5, help_text='0.0 (trivial) to 1.0 (critical). Used for retrieval prioritization.'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['importance'], name='core_memory_importa_415a59_idx'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['importance', 'memory_tier', 'is_active'], name='core_memory_importa_13cbdb_idx'),
        ),
    ]
